### ISSUE TITLE
[Review/Raehan] 좋은 코드 잘 봤습니다. 감사합니다.

### ISSUE THREAD

**Issue by rae-han** [twoLoop-40/booklist#1]
안녕하세요. 좋은 코드 보게해주셔서 감사합니다. 특히 utils 폴더 부분의 로직을 잘 봤습니다.
그리고 Seo로 빼서 공통된 부분을 관리하는 것도 배웠습니다.

추가로 궁금한게 있습니다. 
index 페이지에서 asyncPipe 내부 x 값은 undefined로 이해 했는데 맞을까요??
그리고 내부에서 리턴해주는 함수는 커링한 함수를 만들기 위함 같은데 제가 흐름 읽을게 api 요청을 위한 url을 만드는 함수를 선언하고 그 url을 fetcher 함수에 넣는 함수를 선언한 후 x 값을 넣는 순간 url을 만드는 함수는 평가하면서 코드가 돌아갈거 같은데 맞을까요?

혹시 asyncPipe를 제 스타일에 맞게 와래와 같이 짜봤는데 궁금합니다.

```
export function asyncPipe1 (...fns) {
  return async (x) => {
    let result = x;
    let iter;
    try {
      fns = fns[Symbol.iterator]();

      while (iter = fns.next()) {
        result = await iter(result);
      }

      return result;
    } catch (err) {
      console.error(err);
    }
  };
}

export function asyncPipe2 (...fns) {
  return function* (x) {
    let result = x;

    try {
      for (const fn of fns) {
        result = yield fn(result)
      }

    } catch (err) {
      console.error(err);
    }
  }
}
```

**Comment by twoLoop-40** [comment]
네 맞습니다. index에서 x는 undefined이고 돌아가는 원리도 맞습니다. 
asyncPipe1은 저의 asyncPipe와 완전히 같은 함수이구요. asnycPipe2의 리턴값을 다시 실행하면 제네레이터가 나올거 같은데 그 제네레이터의 next의 value들을 generator로 돌려주고 주고 받아야 같은 함수가 될거 같습니다.

**Comment by rae-han** [comment]
@twoLoop-40 감사합니다. 답글로도 배웠습니다!
